
---
dist: bionic
language: minimal

jobs:
  include:

    - stage: release
      install:
        - wget https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh
        - sudo bash install.sh
        - nvm install lts/*
        - npm i -D semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/exec @commitlint/cli @commitlint/config-conventional
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          all_branches: true 

notifications:
  slack:
    secure: Hau4S83kSsCvrqJWgCGl4SvzqwiOyo3zSLYKqIjEL86N/A6l/8Rvm9JqKD0lpexDGqWeAWN2K0SH4NqGUOLxdNwn+iae/MpGkLNSaKQq4hK3fG65pxkgxKbzelFsI+Ah77iT0K3eKJ2O8EAIZeae7aVpalfMVnZ4VR+ddaSGt5jqyu2i2UXC2qH2Nw7aawYjGPeEJ6L1R4pejluqhiuDVTm3oN/YS5QYOWFUyv269lXGVNBdqs5uWjO83USoT7TeNJsw4aO3TioJ6K6uuBaBk0VQSVSjvz/HC00BbXFq3auLU3V842haJJdlZ39FW3b/Ru4M1ol+o47/G1apXocU3sFHvlGQahJQncIEYCkzcY5S3oqJ37ytQbG4RY+xvAk6i9ceE3vzzAT3Q5RuwENozvO6LLW6S/ewxqY7kGQeBqLJAFWZDCHM+AV/zpyggo6yHIXCV63dbYmPEEjIKhg3LZmYQGP8Fk/xH+zq+BqZ3iFXNvRj1/vHg8TYPBN0qmeh4Q8/L7I6Ap99NXvhb+1Qc2wGc7xxn367UdeLzNJSNhYkF6BNi9qQqHT3erbp7VdoL2UmiET+Y3gPGI4uuqcOdipnuYitk5yhIdlQ7KHCouFLLAswhquSTo+5Wi1oiJBQPxerMw0tNamzPanUnhIjGrf6o/72r2EMygy0hYgv1UY=
